//
// Created by texnoman on 22.08.18.
//

#ifndef PICTURETRANSLATOR_CONFIGURATION_H
#define PICTURETRANSLATOR_CONFIGURATION_H

#define DISTANCE_PRECISION 0.005
#define TIMEPATH_PRECISION 0.001
#define MANIPULATOR_TIME_DESCRET 0.05

#define MANIPULATOR_POSITION_X 0
#define MANIPULATOR_POSITION_Y 0

#define WORKSPACE_SIZE_X 0.21
#define WORKSPACE_SIZE_Y 0.297


#endif //PICTURETRANSLATOR_CONFIGURATION_H
