//
// Created by texnoman on 22.08.18.
//

#ifndef PICTURETRANSLATOR_CONFIGURATION_H
#define PICTURETRANSLATOR_CONFIGURATION_H

#define DISTANCE_PRECISION 0.005
#define TIMEPATH_PRECISION 0.01

#endif //PICTURETRANSLATOR_CONFIGURATION_H
